Ext.define('SEMTI.view.portada.Semti' ,{
    extend: 'Ext.panel.Panel',
	alias: 'widget.panelsemti',
	title: 'SEMTI',
	layout: 'fit',
	cls: 'semti',
	autoScroll: true,
	html: "<table class='semti_content' width='100%' height='100%' border='0' cellspacing='0' cellpadding='0'><tr><td valign='top'><div id='subtitle'>BIENVENIDO A NUESTRO MUNDO !!</div><img src='resources/images/caja.png' align='right' id='img_portada1' /><p>SEMTI es un servicio privado cubano especializado en tecnolog&iacute;as de la informaci&oacute;n que tiene como objetivo el desarrollo de Software a la medida, bajo principios de creatividad, agilidad, profesionalidad y responsabilidad como valores compartidos.</p><p>Somos el impulso tecnol&oacute;gico hacia un desarrollo sostenible de la productividad obrera en el entorno empresarial cubano. Promovemos el uso de aplicaciones inform&aacute;ticas en funci&oacute;n de los procesos de gesti&oacute;n que se llevan a cabo en las &aacute;reas de regulaci&oacute;n y control de empresas nacionales.  </p><p>Fomentamos el empleo de tecnolog&iacute;as libres y bajo esta pol&iacute;tica apoyamos las estrategias del pa&iacute;s respecto a la migraci&oacute;n de la plataforma windows hacia el Software libre, es por ello que nuestros productos se convierten en el brazo tecnol&oacute;gico de su empresa as&iacute; como la alternativa mas inteligente y oportuna.</p><br><div id='subtitle' style='margin-top:10px;'>INTEGRACI&Oacute;N SEMTI - POL&Iacute;TICA ECON&Oacute;MICA DE CUBA</div><img src='resources/images/pcc.png' align='left' id='img_portada2' /><p>La Pol&iacute;tica Econ&oacute;mica de nuestro Partido Comunista, reorientada en su 6to Congreso a trav&eacute;s de su proyecto de Lineamientos promueve el uso de la innovaci&oacute;n en funci&oacute;n de elevar la productividad y aprovechamiento laboral en el sector empresarial cubano, en tal sentido, SEMTI constituye la mejor opci&oacute;n para que su empresa se integre a la revoluci&oacute;n econ&oacute;mica que hoy se lleva a cabo en nuestro pa&iacute;s.</p><p><i>''La batalla econ&oacute;mica constituye hoy, m&aacute;s que nunca, la tarea principal y el centro del trabajo ideol&oacute;gico de los cuadros, porque de ella depende la sostenibilidad y preservaci&oacute;n de nuestro sistema social.''</i></p><p><div style='float:left'>Ra&uacute;l Castro Ruz<br>Clausura del IX Congreso de la UJC, 4 de Abril de 2010</div></p><br>&nbsp;<br>&nbsp;</td></tr></table>"	
});
